### PR TITLE
Pressure sensor

### PR DESCRIPTION
**Pull request by chenggong-zhang**
The pressure sensor has been tested successfully and it can connect with imu through qwiic. 
I give some data that I collect
a split version for pressure test
a steering angle + pressure -- as controller with 2 parameters 
some test verified video
https://drive.google.com/drive/folders/1jT8kPPRp7tJVlWDlRVi0jjUQUPinnJ0a?usp=share_link (use UCLA email to watch)

### CODE REVIEW

**Comment by siwei-yuan** [comment]
Great work! But several points to keep in mind:
1. No need to push testing code into the team repo 
2. You can push the data collected, but please provide explanation on it. E.g. Identify the possible range of the value & propose a mapping from pressure to throttle [-1, 1]
3. No need for a steering+pressure ino file. If you are going to integrate them, change the original steering which doesn't have mqtt integrated.
I suggest:
1. Integrate the pressure sensing into the already existed and tested steering angle script to integrate the two (the one without mqtt)
2. Use your pressure sensing script as a header file to be included in the main script (the one with mqtt), so that we can directly call the function to retrive the pressure data and send it through mqtt.

**Comment by siwei-yuan** [comment]
Also, I suggest you to write a function that accepts the max and min value for the pressure sensor's output, as well as the current collected value, and returns the desired throttle output. This is because we haven't made decision on the physcial mechanism to exert force on the pressure sensor, meaning that the max/min values collected can be changing. Linear interpolation can be one of the options.

**Comment by chenggong-zhang** [comment]
1. the test version is an independent script, and only received the pressure sensor print, it makes may help other teammates to test and collect sensor data separately.
2. I will make an explanation on that part, with the maximum and minimum value statistics.
3. just to distinguish the steering version without a sensor integrated or not
4. and 5. thanks for the advice, I will make some changes to that.

**Comment by siwei-yuan** [comment]
If you commit like this, we now have 1. steering only tesing 2. pressure only testing 3. steering + pressure testing. That's redundant and doesn't distinguish "the steering version without a sensor integrated or not". Consider changing.

**Comment by siwei-yuan** [comment]
Also, if you want to help teammates understand the code, write comments. I cannot understand why you commented out line 63-70 in the test file.

**Comment by chenggong-zhang** [comment]
I see, thanks for your suggestion. Working on changing that.

**Pull request closed without merging**
